---
title: "PCA"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```

Since not all peaks are well resolved with XCMS, I'll check which are the 
detected peaks by XCMS and then I'll integrate them manually.

# Preliminaries

```{r preliminaries}
polarity <- "POS" # specify "POS" or "NEG"

if(polarity == "NEG"){
  int = TRUE
} else {
  int = FALSE
}

library(xcms)
library(CompoundDb)
library(BioMark)
library(plotly)
load(paste0("data/RData/data_XCMS_", polarity, ".RData"))
features <- data.frame(featureDefinitions(xdata))
```

# Compound list

```{r}
if(polarity == "NEG"){
  mzvals <- c(321.17391, 311.1685, 
              163.1129, 339.2327,
              174.9562, 190.9284, 242.9435, 304.9139)
  rtvals <- c(591, 604, rep(717,2), rep(839, 4))
} else if(polarity == "POS"){
  mzvals <- c(61.0644, 103.1114, 121.1220, 145.0169, 205.0744, 285.1536,
              243.1827, 485.3578, 
              573.2502,
              274.2737, 274.2737+1.003355, 296.2556, 
              230.2475,
              rep(288.2891, 2),
              81.5202, 90.5255, 102.0335, 125.9858, 167.0124, 255.9437)
  rtvals <- c(rep(78, 6), rep(196, 2), 407, rep(440, 3), 441, 464, 474, 
              rep(840, 6))
}

cmps.mx <- matrix(nrow = length(mzvals), ncol = 4)
colnames(cmps.mx) <- c("mzmin", "mzmax", "rtmin", "rtmax")
for(i in 1:length(mzvals)){
  cmps.mx[i,1] <- mzvals[i] - 0.01
  cmps.mx[i,2] <- mzvals[i] + 0.01
  cmps.mx[i,3] <- rtvals[i] - 10
  cmps.mx[i,4] <- rtvals[i] + 20
}
if(polarity == "NEG"){
  cmps.mx[2,4] <- 630
  cmps.mx[3:4, 3:4] <- c(rep(710,2), rep(730,2))
  cmps.mx[5:8,4] <- 870
}
if(polarity == "POS"){
  cmps.mx[1:6,4] <- 120
  cmps.mx[10:12,3] <- 420
  cmps.mx[13,3] <- 425
  cmps.mx[14,3:4] <- c(460, 469)
  cmps.mx[15,3:4] <- c(471, 485)
  cmps.mx[16:21,4] <- 890
}
```

# Peak integration

```{r}
register(SerialParam())
manual <- manualChromPeaks(data_raw,
                           chromPeaks = cmps.mx,
                           samples = seq_along(fileNames(data_raw)),
                           BPPARAM = bpparam(),
                           msLevel = 1L)

data.long <- data.frame(chromPeaks(manual))
data <- data.frame(matrix(ncol = length(mzvals), nrow = length(xdata$filename)))
for(i in 1:ncol(data)){
  for(j in 1:length(xdata$filename)){
    dt_tmp <- data.long[data.long$sample == j,]
    if(length(unlist(matchWithPpm(mzvals[i], dt_tmp$mz, ppm = 10)))>0){
      dt_tmp <- dt_tmp[unlist(matchWithPpm(mzvals[i], 
                                           dt_tmp$mz, ppm = 10)), ]
      if(nrow(dt_tmp) > 1){
        dt_tmp <- dt_tmp[which.min(abs(rtvals[i] - dt_tmp$rt)), ]
      }
      data[j,i] <- dt_tmp$into[unlist(matchWithPpm(mzvals[i], 
                                                   dt_tmp$mz, ppm = 10))]
    }
  }
}
colnames(data) <- paste0("mz", round(mzvals), "_rt", round(rtvals))
rownames(data) <- gsub(".mzData", "", xdata$filename)
```

# Peak areas

```{r}
col_filter <- c("#000000", "#DF536B", "#61D04F", "#2297E6")
names(col_filter) <- c("nonfilter", "milex", "clarify", "minisart")
for(i in 1:nrow(cmps.mx)){
  register(SerialParam())
  chr <- chromatogram(
    manual, 
    mz = c(cmps.mx[i,"mzmin"], cmps.mx[i,"mzmax"]), 
    rt = c(cmps.mx[i,"rtmin"] - 10, cmps.mx[i,"rtmax"] + 10)
  )
  pk_col <- col_filter[as.character(
  chr$filter[chromPeaks(chr)[, "sample"]])]
  plot(chr,peakPch = 16, 
                     peakCol = paste0(pk_col, 80),
                     peakBg = paste0(pk_col, 10))
  abline(v=c(cmps.mx[i,"rtmin"], cmps.mx[i,"rtmax"]), 
         col = "red", lty = 2)
}
```


# PCA

```{r}
dt <- t(data)
dt <- t(imputeRowMinRand(dt, method = "from_to",
                         min_fraction = 1/100,
                         min_fraction_from = 1/1000
))
dt <- log10(dt)
scaling.pareto <- scalefun(sc.p="pareto")
dt <- data.frame(scaling.pareto(dt))
pca <- prcomp(dt, center = FALSE, scale. = FALSE)
tmp <- data.frame(pca$x)
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text = rownames(tmp),
        color = xdata$solvent, symbol = xdata$filter)
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text =rownames(tmp),
        color = xdata$solvent)
plot_ly(x = tmp$PC1, y = tmp$PC2,
        text =rownames(tmp),
        color = xdata$filter)

tmp <- data.frame(pca$rotation)
plot_ly(x = tmp$PC1, y = tmp$PC2,
        mode = 'text', text = rownames(tmp))
```

```{r eval=int}
data[is.na(data)] <- 0
plot(data$mz163_rt717, col = col_filter[xdata$filter],  
     pch = c(16,8,3,4)[factor(xdata$solvent)], xlab = "", ylab = "")
legend("topleft", col = col_filter, pch = 16, 
       legend = names(col_filter), ncol = 2)
legend("topright", pch = c(16,8,3,4), 
       legend = levels(factor(xdata$solvent)), ncol = 2)

plot(data$mz339_rt717, col = col_filter[xdata$filter],  
     pch = c(16,8,3,4)[factor(xdata$solvent)], xlab = "", ylab = "")

plot(data$mz311_rt604, col = col_filter[xdata$filter],  
     pch = c(16,8,3,4)[factor(xdata$solvent)], xlab = "", ylab = "")

plot(data$mz191_rt839, col = col_filter[xdata$filter],  
     pch = c(16,8,3,4)[factor(xdata$solvent)], xlab = "", ylab = "")
```

# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```