---
title: "XCMS processing"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```


# Preliminaries

## Parameters

```{r parameters}
polarity <- "POS" # specify "POS" or "NEG"
if(polarity == "POS"){
  int <- 1000000
} else if(polarity == "NEG"){
  int <- 500000
}
```


## Libraries

```{r libraries, message = FALSE}
library(xcms)
```


# Data import

```{r data-import}
#  Get filenames
injections <- data.frame(
  filename = list.files(paste0("data/", polarity, "_fixed/"))
)
tmp <- strsplit(gsub(".mzData", "", injections$filename), "_")
tmp <- data.frame(do.call(rbind, tmp))
colnames(tmp) <- c("order", "solvent", "filter", "polarity", "repl")
injections <- cbind(injections, tmp)
rm(tmp)


# Read the data
data_raw <- readMSData(
  paste0("data/", polarity, "_fixed/" , injections$filename),
  pdata = as(AnnotatedDataFrame(injections),
             "NAnnotatedDataFrame"), 
  mode = "onDisk")
```


# Peak detection

```{r peak-detection}
cwp <- CentWaveParam(ppm = 20,
                     peakwidth = c(2, 20),
                     prefilter = c(5, int),
                     snthresh = 5,
                     noise = 1000,
                     mzdiff = 0.001,
                     integrate = 2)
xdata <- findChromPeaks(data_raw, param = cwp)
```


## Filter low-intensity peaks

```{r filter-intensity}
xdata <- refineChromPeaks(xdata, 
                          param = FilterIntensityParam(
                            nValues = 5, threshold = int)
)
```


## Peak post-processing

```{r peak-postproc}
mnp <- MergeNeighboringPeaksParam(
  expandRt = 2, 
  expandMz = 0.001, 
  ppm = 10,
  minProp = 0.66)
register(SerialParam())
xdata <- refineChromPeaks(xdata, param = mnp)
```



# Correspondance

```{r correspondance}
pdp <- PeakDensityParam(
  sampleGroups = paste(xdata$solvent, xdata$filter, sep = "_"),
  minFraction = 1,
  minSamples = 3,
  binSize = 0.02,
  bw = 1)
xdata <- groupChromPeaks(xdata, param = pdp)
```


# Peak filling

```{r peak-filling}
fcp <- ChromPeakAreaParam()
xdata <- fillChromPeaks(xdata, param = fcp)
```

# Save data

```{r save}
save(data_raw, xdata, file = paste0("data/RData/data_XCMS_", polarity, ".RData"))
```


# Session information

```{r session}
Sys.time()-startpoint
devtools::session_info()
```